# spring.application.name=micro-gateway
server:
  port: ${PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: https://micro-eureka-v2.onrender.com/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: micro-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'